### ISSUE TITLE
AttributeError: 'SoftSequence' object has no attribute 'decode'

### ISSUE THREAD

**Issue by wjczf123** [INK-USC/TriggerNER#3]
Hi,
  I run your code semi_supervised.py found this error:
Traceback (most recent call last):
  File "semi_supervised.py", line 191, in <module>
    main()
  File "semi_supervised.py", line 188, in main
    sequence_trainer.self_training(20, dataset, unlabeled_x)
  File "/deepo_data/CZF/TriggerNER-master/model/soft_inferencer.py", line 219, in self_training
    weaklabel, unlabel = self.weak_label_selftrain(unlabels, self.triggers)
  File "/deepo_data/CZF/TriggerNER-master/model/soft_inferencer.py", line 283, in weak_label_selftrain
    weakly_labeled, unlabeled, confidence = self.weakly_labeling(batched_data, unlabeled_data, triggers)
  File "/deepo_data/CZF/TriggerNER-master/model/soft_inferencer.py", line 254, in weakly_labeling
    batch_max_scores, batch_max_ids = self.model.decode(*batch[0:5], triggers)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'SoftSequence' object has no attribute 'decode'.

I found that the 'SoftSequence' object has no attribute 'decode' indeed. Is this a bug or a problem with my operation. Thanks!

**Comment by danny911kr** [comment]
Thank you so much for your comment! 
I just updated the code.

Thanks again!

**Comment by wjczf123** [comment]
Thank you!
